apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-sample-api
  namespace: argocd
spec:
  destination:
    namespace: cicd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/devpandai/go-sample-deploy.git
    targetRevision: main
    path: .
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
