apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-sample-api
  namespace: cicd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-sample-api
  template:
    metadata:
      labels:
        app: go-sample-api
    spec:
      imagePullSecrets:
      - name: harbor-secret   # <-- ganti sesuai secret Harbor
      containers:
      - name: go-sample-api
        image: registry.pimen.web.id/library/go-sample-api:13
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
