apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-sample-api
  namespace: cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-sample-api
  template:
    metadata:
      labels:
        app: go-sample-api
    spec:
      containers:
        - name: go-sample-api
          image: ghcr.io/devpandai/go-sample-api:latest
          ports:
            - containerPort: 8080
