apiVersion: v1
kind: Service
metadata:
  name: go-sample-api
  namespace: cicd
spec:
  type: NodePort
  selector:
    app: go-sample-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
